apiVersion: "autoscaling.openshift.io/v1beta1"
kind: "MachineAutoscaler"
metadata:
  name: "memory-node-zone1"
  namespace: "openshift-machine-api"
spec:
  minReplicas: 1 
  maxReplicas: 3
  scaleTargetRef: 
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet 
    name: memory-node-zone1