apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: arodemo-northeurope-c-b24pq #Cluster Name
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
  name: memory-node-zone1 #Nodes Name Prefix, all newly created machines will use this prefix 
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: arodemo-northeurope-c-b24pq #Cluster Name 
      machine.openshift.io/cluster-api-machineset: memory-node-zone1 #Nodes Name Prefix, all newly created machines will use this prefix 
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: arodemo-northeurope-c-b24pq #Cluster Name 
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: memory-node-zone1 #Nodes Name Prefix, all newly created machines will use this prefix   
    spec:
      metadata:
        labels:
          machineset-name: memory-node-zone1    ##This is a custom label that will be added to the nodes created by this machineset, this will be needed during the autoscaling excerise
      providerSpec:
        value:
          apiVersion: azureproviderconfig.openshift.io/v1beta1
          credentialsSecret:
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          image:
            offer: aro4
            publisher: azureopenshift
            sku: aro_48
            version: 48.84.20210630
          kind: AzureMachineProviderSpec
          location: northeurope
          networkResourceGroup: arodemo-northeurope-cluster-master-rg
          osDisk:
            diskSizeGB: 128
            managedDisk:
              storageAccountType: Premium_LRS
            osType: Linux
          publicIP: false
          publicLoadBalancer: arodemo-northeurope-c-b24pq
          resourceGroup: arodemo-northeurope-cluster-nodes-rg
          subnet: arodemo-northeurope-cluster-workers-subnet
          userDataSecret:
            name: worker-user-data
          vmSize: Standard_E4s_v3
          vnet: arodemo-northeurope-cluster-vnet
          zone: "1"
